version: '2'
services:
  covid-app:
    image: covid
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://covid-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=covid
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  covid-mongodb:
    extends:
      file: mongodb.yml
      service: covid-mongodb
